@startuml
skinparam sequenceMessageAlign center
Main "0..1" --> "0..*" VideoClub : Contiene
Main "0..1" --> "0..*" Pelicula: Utiliza
Main "0..1" --> "0..*" Cliente: Usa
Main "0..1" --> "0..1" Interface: Incluye
Main "0..1" --> "0..*" Funciones: Llama

VideoClub "1" --> "0..*"  Cliente: Atiende
VideoClub "1" --> "1..*"  Pelicula:  Posee
Cliente "1" --> "0..*" Arriendo: Accede
Interface "1" --> "1..*" Funciones: Invoca

class VideoClub{
    -String  nombreTienda
    -String  direccion
    -ArrayList<Pelicula> listaPeliculas
    -ArrayList<Cliente>   listaClientes
    -HashMap<String,Pelicula> pelisXId
    -HashMap<String,Cliente> clientesXRut
    __
    .. Constructor ..
    +VideoClub()
    .. Setter/Getter..
    +String getNombreTienda()
    +void setNombreTienda(String nombreTienda)
    +String getDireccion()
    +void setDireccion(String direccion)
    .. Agregar a colecciones ..
    +void addPeliToListaPelis(Pelicula peli)
    +void addClientToListaClients( Cliente cliente)
    +void addClientToClientXRut(String rut, Cliente cliente)
    +void addPeliToPelisXId(String id, Pelicula peli)
    .. Mostrar datos por pantalla..
    +void mostrarDatosPeliculas()
    +void mostrarDatosClientes(String rut)
    +void mostrarDatosPeliculas()
    +void mostrarDatosPeliculas(String id)
    .. Obtener elementos de colecciones..
    +Cliente getClientFromClientXRut(String rut)
    +Pelicula getPeliFromPelisXId(String id)
    .. Otros métodos ..
    +boolean containsID(String id)
    +boolean containsRUT(String rut)
    +boolean existID(String id)
    +boolean existRUT(String rut)
    +String obtenerIdXNombre(String nombre)
    +int getSize(int modo)
}

class Cliente{
    -String nombre
    -String rut
    -ArrayList<Arriendo> historialArriendos
    -HashMap<String, Arriendo> historialXid
    -int deuda

    +Cliente()
    +Cliente(String nombre, String rut)
    +String getNombre()
    +void setNombre(String nombre)
    +String getRut()
    +void setRut(String rut)
    +void addArriendoToHistorial(Arriendo arriendo)
    +int getDeuda()
    +void setDeuda(int deuda)
    +void addToHistorialXid(Arriendo arriendo)
    +void mostrarHistorial()
    +void mostrarHistorial(String id)
    +boolean existIDMap(String id)
}

class Pelicula{
    -String nombre
    -String id
    -short existencias
    -short disponibles
    -float valuacion
    -short cantValuaciones
    -short añoEstreno
    -short duraciónMin
    -String sinopsis
    -String calidad
    -String director[]
    -String actores[]
    -String generos[]

    +Pelicula()
    +String getNombre()
    +void setNombre(String nombre)
    +String getId()
    +void setId(String id)
    +short getExistencias()
    +void setExistencias(short existencias)
    +short getDisponibles()
    +void setDisponibles(short disponibles)
    +float getValuacion()
    +void setValuacion(float valuacion)
    +short getCantValuaciones()
    +void setCantValuaciones(short cantValuaciones)
    +short getAñoEstreno()
    +void setAñoEstreno(short añoEstreno)
    +short getDuraciónMin()
    +void setDuraciónMin(short duraciónMin)
    +String getSinopsis()
    +void setSinopsis(String sinopsis)
    +String getCalidad()
    +void setCalidad(String calidad)
    +String[] getDirector()
    +void setDirector(String[] directores)
    +String[] getActores()
    +void setActores(String[] actor)
    +String[] getGeneros()
    +void setGeneros(String[] genero)
}

class Arriendo{
    -String id
    -float valoracion
    -String fechaArriendo
    -String fechaEntrega
    -boolean entregado
    - int vecesArrendada;

    +Arriendo()
    +String getId()
    +void setId(String id)
    +float getValoracion()
    +void setValoracion(float valoracion)
    +String getFechaArriendo()
    +void setFechaArriendo(String fechaArriendo)
    +String getFechaEntrega()
    +void setFechaEntrega(String fechaEntrega)
    +boolean isEntregado()
    +void setEntregado(boolean entregado)
    +void setVecesArrendada(int vecesArrendada)
    +int getVecesArrendada()
}

class Main{
    +static void main(String[] args)
}

class Interface{
    +static void login()
    +static void menúCliente(String usuario,VideoClub x)
    +static void menúAdmin(VideoClub x)
}

class Funciones{
    + static void listaPeliculas(VideoClub x)
    + static void listaClientes(VideoClub x)
    + static void mostrarHistorialCliente(VideoClub x, String rut)
    + static void mostrarHistorialPeli(VideoClub x, String rut)
    + static void registrarCliente(VideoClub x)
    + static void registrarPelicula(VideoClub x)
    + static String[] ingresoDirectores(Scanner teclado)
    + static String[] ingresoGeneros(Scanner teclado)
    + static String[] ingresoActores(Scanner teclado)
    + static float ingresoValuacion(Scanner teclado)
    + static void buscarPelicula(VideoClub x)
    + static void desplegarMiFicha(VideoClub x, String usuario)
    + static void historialCliente(VideoClub x)
    + static void buscarCliente(VideoClub x)
    + static void LeerArchivoClientes(VideoClub videoClub, Cliente cliente)
    + static void LeerArchivoPeliculas(VideoClub videoClub, Pelicula pelicula)
}
@enduml